[package]
name = "counter_static_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "counter_static_lib"
crate-type = ["lib"]

[dependencies]
libc = "0.2"